#!/usr/bin/env python3

# Copyright (c) 2018 Kristofer Berggren
# All rights reserved.
#
# idntag is distributed under the MIT license, see LICENSE for details.

import acoustid
import argparse
import base64
import glob
import os
import re
import taglib
import time


def rate_limit(min_interval):
    try:
        sleep_duration = min_interval - (time.time() - rate_limit.last_timestamp)
    except AttributeError:
        sleep_duration = 0

    if sleep_duration > 0:
        time.sleep(sleep_duration)

    rate_limit.last_timestamp = time.time()


def cleanstr(str):
    return re.sub(r'\W+', '', str.replace(" ", "_"))


def identify_and_update_file(path, keep_name):
    rate_limit(1.0/3.0)
    print(path + " : ", end='')
    try:
        results = acoustid.match(base64.b64decode(b'Ym5jenB4cmtoOA=='), path)
    except acoustid.NoBackendError:
        print("FAIL : backend library not found")
        return False
    except acoustid.FingerprintGenerationError:
        print("FAIL : fingerprint generation error")
        return False
    except acoustid.WebServiceError as exc:
        print("FAIL : web service error (" + exc.message + ")")
        return False

    for score, rid, title, artist in results:
        song = taglib.File(path)
        song.tags["ARTIST"] = [artist]
        song.tags["TITLE"] = [title]
        song.save()

        newpath = path
        if not keep_name:
            olddir, oldfile = os.path.split(path)
            oldfile, oldext = os.path.splitext(path)
            newpath = olddir + "/" + cleanstr(artist) + "-" + cleanstr(title) + oldext
            # XXX: todo check if file exists before overwriting?
            os.rename(path, newpath)

        print("OK : " + newpath)
        return True

    print("FAIL : no matches found")
    return False


def main():
    parser = argparse.ArgumentParser(prog="idntag", description=
                                     "Identify artist and song name from specified "
                                     "audio files and update their ID3-tag meta-data "
                                     "with correct data, and rename the files on format "
                                     "Artist_Name-Track_Name.")
    parser.add_argument("-k", "--keepname", action="store_true", help="keep original filename")
    parser.add_argument("-v", "--version", action='version', version='%(prog)s v1.03')
    parser.add_argument('path', nargs='+', help='path of a file or directory')
    args = parser.parse_args()

    abs_paths = [os.path.join(os.getcwd(), path) for path in args.path]
    paths = set()
    for path in abs_paths:
        if os.path.isfile(path):
            paths.add(path)
        elif os.path.isdir(path):
            abs_paths += glob.glob(path + '/*')

    for path in paths:
        identify_and_update_file(path, args.keepname)


if __name__ == "__main__":
    main()
