#!/usr/bin/env bash

# test002 - detect english song (without rename)

# Environment
BUILDDIR="$(pwd)"
TMPDIR=$(mktemp -d)
pushd ${TMPDIR} > /dev/null

# Update tag and keep filename
RV="0"
cp ${BUILDDIR}/../tests/song_en.mp3 ${TMPDIR}/song_en.mp3
${BUILDDIR}/idntag -d song_en.mp3

# Test filename
FILELIST=$(ls -1)
EXPECTED="song_en.mp3"
if [[ "${FILELIST}" != "${EXPECTED}" ]]; then
  echo "\"${FILELIST}\" != \"${EXPECTED}\""
  RV="1"
fi

# Test artist tag
ARTIST=$(mp3info -p %a *.mp3)
EXPECTED="Broke For Free"
if [[ "${ARTIST}" != "${EXPECTED}" ]]; then
  echo "\"${ARTIST}\" != \"${EXPECTED}\""
  RV="1"
fi

# Test title tag
TITLE=$(mp3info -p %t *.mp3)
EXPECTED="Night Owl"
if [[ "${TITLE}" != "${EXPECTED}" ]]; then
  echo "\"${TITLE}\" != \"${EXPECTED}\""
  RV="1"
fi

# Cleanup
popd > /dev/null
rm -rf ${TMPDIR}
exit ${RV}
