#!/usr/bin/env bash

# test004 - detect and rename english song

# Environment
BUILDDIR="$(pwd)"
TMPDIR=$(mktemp -d)
pushd ${TMPDIR} > /dev/null

# Update tag and keep filename
RV="0"
cp ${BUILDDIR}/../tests/song_en.mp3 ${TMPDIR}/song_en.mp3
${BUILDDIR}/idntag -d -r song_en.mp3 > ${TMPDIR}/out.txt 2> ${TMPDIR}/err.txt

# Test result
RESULT="$(cat ${TMPDIR}/out.txt | awk -F ' : ' '{ print $2 }')"
EXPECTED="PASS"
if [[ "${RESULT}" != "${EXPECTED}" ]]; then
  echo "\"${RESULT}\" != \"${EXPECTED}\""
  RV="1"
fi

# Test resulting filename
FILEPATH="$(realpath "$(cat ${TMPDIR}/out.txt | awk -F ' : ' '{ print $3 }')")"
EXPECTED="$(realpath "${TMPDIR}/Broke_For_Free-Night_Owl.mp3")"
if [[ "${FILEPATH}" != "${EXPECTED}" ]]; then
  echo "\"${FILEPATH}\" != \"${EXPECTED}\""
  RV="1"
fi

# Cleanup
popd > /dev/null
rm -rf ${TMPDIR}
exit ${RV}
