#!/usr/bin/env bash

# test007 - detect tags and then clear them

# Environment
BUILDDIR="$(pwd)"
TMPDIR=$(mktemp -d)
pushd ${TMPDIR} > /dev/null

# Update tag and filename
RV="0"
cp ${BUILDDIR}/../tests/song_en.mp3 ${TMPDIR}/song_en.mp3
${BUILDDIR}/idntag -d -r song_en.mp3

# Test filename
FILELIST=$(ls -1)
EXPECTED="Broke_For_Free-Night_Owl.mp3"
if [[ "${FILELIST}" != "${EXPECTED}" ]]; then
  echo "\"${FILELIST}\" != \"${EXPECTED}\""
  RV="1"
fi

# Clear tags
RV="0"
${BUILDDIR}/idntag -c *.mp3
if [[ "${?}" != "0" ]]; then
  echo "idntag -c != 0"
  RV="1"
fi

# Test artist tag
ARTIST=$(mp3info -p %a *.mp3)
EXPECTED=""
if [[ "${ARTIST}" != "${EXPECTED}" ]]; then
  echo "\"${ARTIST}\" != \"${EXPECTED}\""
  RV="1"
fi

# Test title tag
TITLE=$(mp3info -p %t *.mp3)
EXPECTED=""
if [[ "${TITLE}" != "${EXPECTED}" ]]; then
  echo "\"${TITLE}\" != \"${EXPECTED}\""
  RV="1"
fi

# Cleanup
popd > /dev/null
rm -rf ${TMPDIR}
exit ${RV}
